[Backend] Create Product Rating API
dandalandone/POC-EyCommerce pull request #106
Opened 2023-09-14 05:13 UTC by 5andrex

## Ticket/s

- [Create Product Rating](https://trello.com/c/NRhiuXzC/42-api-creation-product-rating)

## Changes

- Add create rating DTO, rating Service, and rating Controller
- Add Create Product Rating API
- Modify Order Service --- add `getAllDeliveredOrders`

## Screenshot

- Rating created successfully

![image](https://github.com/TreshAnn/POC-EyCommerce/assets/129832182/7dbb37c2-13c3-4b3f-8d04-3d72f137bd5f)

- Exception: Rating already exists in Product

![image](https://github.com/TreshAnn/POC-EyCommerce/assets/129832182/34a22a83-8de6-4057-9b2a-c899302c0c38)

- Exception: Product does not exist in Delivered Orders

![image](https://github.com/TreshAnn/POC-EyCommerce/assets/129832182/e84f8a7a-e03d-455a-849e-d29c16948df7)

## How to test?

- open Postman
- add products to Cart - [Add Item to Cart PR](https://github.com/TreshAnn/POC-EyCommerce/pull/84)
- create Order from products in Cart - [Create Order PR](https://github.com/TreshAnn/POC-EyCommerce/pull/97)
- create order with different `status`: "processing", "shipped", "delivered"
- get all delivered products using cURL:
```
curl --location 'localhost:3001/api/order/all-delivered-orders/' \
--header 'Authorization: Bearer 
<auth token here>
'
```
- create rating using `productId` in `allDeliveredOrders`
```
curl --location 'localhost:3001/api/rating/create' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer 
<auth token here>
' \
--data '{
    "productId": "<productId from allDeliveredOrders here>",
    "rating": 5,
    "title": "rating title",
    "description": "rating description"
}
'
```

2023-09-14 10:25 UTC, TreshAnn requested changes
When I tested this in Postman with an existing order having the status "delivered," I encountered the following error:
{
    "message": "Product not found in delivered order",
    "error": "Not Found",
    "statusCode": 404
}

![image](https://github.com/TreshAnn/POC-EyCommerce/assets/126449551/709b9603-1ab3-4e08-837f-ea7d87d04131)

![image](https://github.com/TreshAnn/POC-EyCommerce/assets/126449551/2023458a-9366-4545-b8be-50d971e00a2f)

2023-09-15 02:42 UTC, TreshAnn commented on apps/api/src/rating/dto/create-rating.dto.ts
> +import { Type } from 'class-transformer';
remove this
```suggestion
```

2023-09-15 02:47 UTC, TreshAnn commented on apps/api/src/rating/dto/create-rating.dto.ts
> +  })
```suggestion
  @isValidRating()
```


add this to custom-validation.utils.ts
```
export function isValidRating(options?: ValidationOptions): PropertyDecorator {
  return function (object: Record<string, any>, propertyName: string) {
    registerDecorator({
      name: 'isValidRating',
      target: object.constructor,
      propertyName: propertyName,
      options: options,
      validator: {
        validate(value: any): boolean {
          return typeof value === 'number' && value >= 1 && value <= 5;
        },
        defaultMessage(): string {
          return 'Rating must be a number between 1 and 5.';
        },
      },
    });
  };
}
```

2023-09-15 02:49 UTC, TreshAnn submitted a review, later dismissed

2023-09-15 03:08 UTC, SGVGen approved these changes
Tested & LGTM!

2023-09-15 06:30 UTC, brentmillen commented on apps/api/src/order/order.service.ts
some functions are part of this PR, please check to avoid duplicate functions:
https://github.com/TreshAnn/POC-EyCommerce/pull/105

2023-09-15 06:30 UTC, brentmillen commented on apps/api/src/rating/rating.controller.ts
avoid redundant naming of controllers and url:

ex. 
api/rating/create --> api/rating (since this is the only Post request)
createRating --> create

this controller is already dedicated to ratings only, no need to name some functions/controllers with 'rating'

2023-09-15 06:50 UTC, 5andrex commented on apps/api/src/rating/rating.controller.ts
noted, will apply these changes. thanks!

2023-09-16 16:25 UTC, markjoshuacarmen approved these changes
lgtm

2023-09-18 00:58 UTC, TreshAnn approved these changes

2023-09-18 07:51 UTC, brentmillen approved these changes

2023-09-18 10:08 UTC, TreshAnn commented on apps/api/src/rating/rating.service.ts
> +
it might be more efficient to utilize the userId from the request payload
```suggestion
    const userId = req._id;
```

2023-09-18 11:52 UTC, merged