Feat/backend/update rating api
dandalandone/POC-EyCommerce pull request #108
Opened 2023-09-18 01:51 UTC by markjoshuacarmen

## Ticket/s

- [Update rating API](https://trello.com/c/g6RpVVau/44-api-update-product-rating)

## Changes

- add update-rating-schema
- add update-rating services

## Screenshot
![image](https://github.com/TreshAnn/POC-EyCommerce/assets/129832464/d059c560-7582-4356-9202-97f4c172b265)

![image](https://github.com/TreshAnn/POC-EyCommerce/assets/129832464/171ce127-2284-4dd2-a932-b2f28a458bfb)

## How to test?

- pnpm run dev
- open postman
- add products to Cart - https://github.com/TreshAnn/POC-EyCommerce/pull/84
- create Order from products in Cart - https://github.com/TreshAnn/POC-EyCommerce/pull/97
- create order with different status: "processing", "shipped", "delivered"
- create product rating https://github.com/TreshAnn/POC-EyCommerce/pull/106
- 
- get all user rating:
`curl --location 'localhost:3001/api/rating/get-user-ratings' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvbnN1bWVyIiwic3ViIjoiNjUwMDAwMTIxZTJlMWJhNGU4MTM2ZGUxIiwiaWF0IjoxNjk0OTk5ODQ4LCJleHAiOjE2OTUwODYyNDh9.4z6O6f9bMOxngoVJfZSDqKyLJpnZHJrwbvhJ9IEsNF4'`

- copy the rating_Id
`curl --location --globoff --request PUT 'localhost:3001/api/rating/update/[place rating_id here]' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvbnN1bWVyIiwic3ViIjoiNjUwMDAwMTIxZTJlMWJhNGU4MTM2ZGUxIiwiaWF0IjoxNjk0OTk5ODQ4LCJleHAiOjE2OTUwODYyNDh9.4z6O6f9bMOxngoVJfZSDqKyLJpnZHJrwbvhJ9IEsNF4' \
--data '{
    "rating" : 4,
    "title": " test ",
    "description": " "
}'`

2023-09-18 11:32 UTC, TreshAnn requested changes

2023-09-18 11:32 UTC, TreshAnn commented on apps/api/src/rating/rating.service.ts
> +    }
After implementing these changes, I suggest you thoroughly test the updateRating function to ensure it functions as expected. As for the time, consider converting updateTime to Philippine Standard Time (PST). not sure if this works, but you can refer to this Stack Overflow post: https://stackoverflow.com/questions/35672248/how-to-change-date-timezone-in-mongoose

```suggestion

    const updateTime = new Date();
    updateTime.setTime(updateTime.getTime() - 2 * 60 * 1000); // 2 minutes for testing only
    //for 5 days updateTime.setDate(updateTime.getDate() - 5);

    if (existingRating.publishedDate < updateTime) {
      throw new BadRequestException(
        'You can only update your review within 2 minutes of the original review',
      );
    }

    if (updatedRatingDto.rating !== undefined) {
      existingRating.rating = updatedRatingDto.rating;
    }
    if (updatedRatingDto.title !== undefined) {
      existingRating.title = updatedRatingDto.title;
    }
    if (updatedRatingDto.description !== undefined) {
      existingRating.description = updatedRatingDto.description;
    }

    existingRating.reviewDate = updateTime;
```

2023-09-19 01:06 UTC, UnknownXD reviewed
Use dayjs, don’t use moment

2023-09-19 08:15 UTC, brentmillen reviewed
see comments

2023-09-19 08:15 UTC, brentmillen commented on pnpm-lock.yaml
remove imported library

2023-09-19 08:15 UTC, brentmillen commented on apps/api/src/rating/rating.service.ts
>      let itemFound = false;
just use an if else state for this

2023-09-19 09:30 UTC, TreshAnn approved these changes

2023-09-20 00:45 UTC, markjoshuacarmen commented on pnpm-lock.yaml
this is noted thanks

2023-09-20 02:48 UTC, merged