feat(frontend): register merchant API implementation
dandalandone/POC-EyCommerce pull request #116
Opened 2023-09-20 14:33 UTC by markjoshuacarmen

## Ticket/s

- [Merchant Registration API](https://trello.com/c/aYME5Zxo/151-merchant-registration)

## Changes

- Register Merchant API Implementation

## Screenshot

![image](https://github.com/TreshAnn/POC-EyCommerce/assets/129832464/bf90e78c-a54c-44fa-8f1c-f3964d43f390)

## How to test?

- register to http://localhost:5173/register
- check db if new merchant is added

2023-09-21 04:13 UTC, 5andrex requested changes
Validation does not work (see attached image).

![image](https://github.com/TreshAnn/POC-EyCommerce/assets/129832182/7fc12b65-2b9c-4384-97fe-0055b21c307e)

2023-09-28 02:15 UTC, 5andrex approved these changes
lgtm

2023-09-28 07:44 UTC, TreshAnn commented on apps/api/src/app.module.ts
> +    MongooseModule.forRoot('mongodb://localhost:27017/test'),
make sure to use the connection string for central db before merging.

2023-09-28 07:46 UTC, TreshAnn approved these changes
LGTM

2023-09-28 20:22 UTC, markjoshuacarmen commented on apps/api/src/app.module.ts
> +    MongooseModule.forRoot('mongodb://localhost:27017/test'),
this is noted thanks

2023-09-28 20:30 UTC, merged