chore(backend): add update product API
dandalandone/POC-EyCommerce pull request #35
Opened 2023-08-02 17:27 UTC by markjoshuacarmen

## Ticket/s
[[API] Update Product](https://trello.com/c/OrWeGjL5/34-api-update-product)

## Changes
- add update product API
- modify product controller
- modify product services

## Screenshot

![image](https://github.com/dandalandone/POC-EyCommerce/assets/129832464/6d6fb20c-b4d9-42a0-b09b-f4ec8fc82bbd)

## How to test?
   1. Create product 
   2. Use this link
   ```
curl --location 'http://localhost:3001/products/create' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZSIsInN1YiI6IjY0YzlmZDExMThlNGYyNzRkZTc1YWYxYSIsImlhdCI6MTY5MDk1OTEzNSwiZXhwIjoxNjkxMDQ1NTM1fQ.ZJ1uOuCfEQvCCOi0QmKq3wG_v6d_SRcQB_SkUKZS04o' \
--data '{
 "productID": "product12",
 "productImg": {
     "ImgURL": "https://example.com/image.jpg",
     "ImgAttch": "base64encodedimage"
 },
 "productName": "Product Name",
 "productInfo": "Product Information",
 "productPrice": 199.99,
 "productInventory": 32,
 "productCategory": [
     "sample",
     "sample1",
     "sample2"
 ]
}'
```
   4. Copy the product Id in Db
   5. Copy the product token in login then paste in the Authorization Bearer in PUTrequest
   6. Import cURL for the PUT request.
```
curl --location --request PUT 'http://localhost:3001/products/update/64ca8db9672d65dcba2471e3' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZSIsInN1YiI6IjY0YzljMThlOGYwODY3NmU3YzgyYzA3NCIsImlhdCI6MTY5MDk0Mzk3OSwiZXhwIjoxNjkxMDMwMzc5fQ.HV-9LG--HZ-73qwY-xX0rkM3wP8ky5Hzu8FQOQ48YzQ' \
--header 'Content-Type: application/json' \
--data '{
    "productID": "change",
    "productImg": {
        "ImgURL": "https://example.com/image.jpg",
        "ImgAttch": "base64encodedimage"
    },
    "productName": "test",
    "productInfo": "Product Information",
    "productPrice": 23,
    "productInventory": 32,
    "productCategory": [
        "sample",
        "sample1",
        "sample2"
    ]
}
'
```
   7. replace <place id here> placeholder with product _id from mongoDB
curl --location 'localhost:3001/products/update/<place id here>'

2023-08-03 05:32 UTC, markjoshuacarmen reviewed
wip(backend): update product API

2023-08-04 03:04 UTC, 5andrex commented
- Product update accepts input beginning and/or ending with spaces (see attached img)
- Use the `custom-validations.utils.ts` in the utils directory 

![image](https://github.com/dandalandone/POC-EyCommerce/assets/129832182/4308387d-2873-4ebb-bb66-7e159dd63b43)

2023-08-04 03:48 UTC, 5andrex requested changes
Please see comment

https://github.com/dandalandone/POC-EyCommerce/pull/35#issuecomment-1664906622

2023-08-04 03:49 UTC, TreshAnn commented
> * Product update accepts input beginning and/or ending with spaces (see attached img)
> * Use the `custom-validations.utils.ts` in the utils directory
> 
> ![image](https://user-images.githubusercontent.com/129832182/258284394-4308387d-2873-4ebb-bb66-7e159dd63b43.png)

same with me. it accepts leading and trailing spaces. As for the Product_Id,  it should not be editable once created

2023-08-04 05:46 UTC, TreshAnn requested changes

2023-08-04 05:46 UTC, TreshAnn commented on apps/api/src/products/products.service.ts
> +    console.log(updatedProduct);
remove this
```suggestion
   
```

2023-08-07 01:51 UTC, markjoshuacarmen commented on apps/api/src/products/products.service.ts
> +    console.log(updatedProduct);
done

2023-08-08 02:32 UTC, 5andrex approved these changes
LGTM!

2023-08-08 03:48 UTC, TreshAnn approved these changes
Working on my end. Thanks, sir!

2023-08-08 05:04 UTC, merged