[Frontend] - Search Bar Component
dandalandone/POC-EyCommerce pull request #37
Opened 2023-08-03 07:56 UTC by 5andrex

## Ticket/s

- [Search Bar Component](https://trello.com/c/D9UbQPCC/23-search-bar-component)

## Changes

- Create Searchbar component 

## Screenshot

#### Figma
![image](https://github.com/dandalandone/POC-EyCommerce/assets/129832182/7c2e6dcb-69f1-4295-927b-968cff7a2841)

#### Actual
![image](https://github.com/dandalandone/POC-EyCommerce/assets/129832182/aabea67c-c499-4780-86a3-60f3a34e776b)

![image](https://github.com/dandalandone/POC-EyCommerce/assets/129832182/26c50738-bff2-4c8a-ad6b-b973205d02d7)

## How to test?

- Run `pnpm run dev` script
- Go to http://localhost:5173

2023-08-04 02:17 UTC, markjoshuacarmen approved these changes
looks nice to me!

2023-08-04 03:07 UTC, TreshAnn approved these changes
LGTM!

2023-08-04 03:38 UTC, dandalandone requested changes, later dismissed

2023-08-04 03:38 UTC, dandalandone commented on apps/web/src/views/SampleView.tsx
> +      {/* <Dropdown /> */}
remove if not used

2023-08-04 03:38 UTC, dandalandone commented on packages/ui/searchbar/searchbar.tsx
> +        height: '70px',
move all styling to styled Components, ask @brentmillen how to move.

2023-08-04 03:38 UTC, dandalandone commented on packages/ui/searchbar/searchbar.tsx
> +              { value: 'latest', label: 'Latest' },
Move mock data to sample file

2023-08-04 06:40 UTC, brentmillen approved these changes
lgtm!

2023-08-04 07:00 UTC, SGVGen commented
LGTM!

2023-08-06 20:32 UTC, UnknownXD approved these changes
LGTM!

2023-08-07 00:35 UTC, merged