[Back-end] Cart Model Schema
dandalandone/POC-EyCommerce pull request #38
Opened 2023-08-04 01:19 UTC by markjoshuacarmen

## Ticket/s
[Cart Model](https://trello.com/c/VAQgfRkD/36-cart-model)

## Changes

- add cart schema 

## Screenshot

- N/A

## How to test?

- N/A

2023-08-04 01:53 UTC, dandalandone approved these changes
LGTM!

2023-08-04 02:19 UTC, TreshAnn requested changes

2023-08-04 02:19 UTC, TreshAnn commented on apps/api/src/cart/schemas/cart.schema.ts
> +  orderedItems: Items;
```suggestion
orderedItems:  Items[]
```

2023-08-04 02:19 UTC, TreshAnn commented on apps/api/src/cart/schemas/cart.schema.ts
> +  product_id: string;
```suggestion
  @Prop({ type: ProductSchema, ref: Product.name })
  product_id: Product;
```

2023-08-04 02:19 UTC, TreshAnn commented on apps/api/src/cart/schemas/cart.schema.ts
> +
Import Product schema here

2023-08-04 02:39 UTC, markjoshuacarmen commented on apps/api/src/cart/schemas/cart.schema.ts
> +
done thanks

2023-08-04 03:06 UTC, TreshAnn approved these changes

2023-08-04 03:39 UTC, dandalandone commented on apps/api/src/cart/schemas/cart.schema.ts
> +  product_id: string;
@markjoshuacarmen no underscore, productID

2023-08-04 03:40 UTC, dandalandone requested changes, later dismissed

2023-08-04 03:40 UTC, dandalandone commented on apps/api/src/cart/schemas/cart.schema.ts
> +  product_id: string;
Make this productId

2023-08-04 09:28 UTC, markjoshuacarmen commented on apps/api/src/cart/schemas/cart.schema.ts
> +  product_id: string;
done change

2023-08-06 20:30 UTC, UnknownXD approved these changes
LGTM!

2023-08-07 00:33 UTC, merged