[Fix] - Fix Create Product API
dandalandone/POC-EyCommerce pull request #41
Opened 2023-08-07 02:09 UTC by KezTimple

## Ticket/s

- [Failed Ticket](https://trello.com/c/BQvSsb8c/32-api-create-product)

## Changes

- Fixed product ID (no spaces)
- Added product creation validation

## Screenshot

- Product ID with space
![image](https://github.com/dandalandone/POC-EyCommerce/assets/137742601/4ff39306-2586-442c-9b13-b6f270e3db10)

- Creation of User
![image](https://github.com/dandalandone/POC-EyCommerce/assets/137742601/8e9c8fc2-c60b-4294-8fce-62c9d5f555f0)

- User log in
![image](https://github.com/dandalandone/POC-EyCommerce/assets/137742601/9e1398db-0487-49d4-8e50-b7dffbbdd282)

- User product creation
![image](https://github.com/dandalandone/POC-EyCommerce/assets/137742601/1c70ac36-9545-46b4-b6ed-318b6ee4529e)

- Creation of Merchant
![image](https://github.com/dandalandone/POC-EyCommerce/assets/137742601/8a6922eb-fd0b-424e-a15f-19db8620b4b4)

- Merchant log in
![image](https://github.com/dandalandone/POC-EyCommerce/assets/137742601/fb19c1a9-326a-4396-893d-a381426752fd)

- Merchant product creation
![image](https://github.com/dandalandone/POC-EyCommerce/assets/137742601/4d4c6e8f-7e68-49ba-ad71-96e6b1c285f8)

## How to test?

- Open Postman and copy cURL to Create Merchant
```
curl --location 'localhost:3001/merchant/create' \
--header 'Content-Type: application/json' \
--data-raw ' {
    "username": "Alpha",
    "email": "alpha@email.com",
    "password": "SeCret!01",
    "userType": "merchant",
    "merchantName": "Merchant'\''s Shop",
    "firstName": "John Carlo",
    "lastName": "Dela cruz",
    "address": {
    "street": "123 Main Street",
    "city": "New York",
    "region": "NY",
    "zipcode": 1000,
    "country": "USA"
  },
  "phoneNumber": "+639212212121"

}'
```
- Log in Merchant (copy cURL)
```
curl --location 'http://localhost:3001/auth/login' \
--header 'Authorization: Bearer' \
--header 'Content-Type: application/json' \
--data '{
    "username": "Alpha",
    "password": "SeCret!01"
}'
```
- Copy access token and add to Headers-Bearer
![image](https://github.com/dandalandone/POC-EyCommerce/assets/137742601/29985213-93b2-4b28-a025-fa75ea71f906)

- Copy cURL to create product
```
curl --location 'http://localhost:3001/products/create' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFscGhhIiwic3ViIjoiNjRkMDRmZmU5MDdlMWUzYjJiMjc0YzgyIiwidXNlcnR5cGUiOiJtZXJjaGFudCIsImlhdCI6MTY5MTM3MzYxNSwiZXhwIjoxNjkxNDYwMDE1fQ.Ffhrmun-D6W6klMnSQuy9LR5QyxzhZbVuM62htiq704' \
--header 'Content-Type: application/json' \
--data '{
    "productID": "product01234",
    "productImg": {
        "ImgURL": "https://example.com/image.jpg",
        "ImgAttch": "base64encodedimage"
    },
    "productName": "Product Name",
    "productInfo": "Product Information",
    "productPrice": 199.99,
    "productInventory": 32,
    "productCategory": [
        "sample",
        "sample1",
        "sample2"
    ]
}'
```

2023-08-07 13:55 UTC, UnknownXD approved these changes
LGTM!

2023-08-08 01:54 UTC, ianchinjen commented
Please remove authorization from the logic as it is on a different ticket.

2023-08-08 03:02 UTC, 5andrex requested changes
Remove product/merchant guard to avoid conflict with authorization ticket as it is being developed by sir @ianchinjen 

[API User Authorization](https://trello.com/c/IjnkaW52/3-api-user-user-authorization)

also remove userType in payload

2023-08-08 03:19 UTC, 5andrex requested changes
Check suggestions @KezTimple thanks!

2023-08-08 03:19 UTC, 5andrex commented on apps/api/src/auth/auth.service.ts
> +      usertype: user.userType,
```suggestion
      
```
 remove `userType` in the payload

2023-08-08 03:19 UTC, 5andrex commented on apps/api/src/products/products.controller.ts
> +  UseGuards,
```suggestion
  
```
remove `UseGuards`

2023-08-08 03:19 UTC, 5andrex commented on apps/api/src/products/products.controller.ts
> +@UseGuards(MerchantGuard)
```suggestion

```
remove `MerchantGuard` and `@UseGuards(MerchantGuard)`

2023-08-08 03:19 UTC, 5andrex commented on apps/api/src/products/product.guard.ts
> +}
```suggestion

```

delete this file

2023-08-08 03:31 UTC, 5andrex approved these changes

2023-08-08 03:49 UTC, TreshAnn approved these changes
LGTM!

2023-08-08 07:44 UTC, merged