[Frontend] - Update Cart API
dandalandone/POC-EyCommerce pull request #47
Opened 2023-08-09 04:01 UTC by TreshAnn

## Ticket/s

- [Update Cart API](https://trello.com/c/hnKHmcH3)

## Changes

- Add Update Cart Item API

## Screenshot
- Current Cart Document 
![image](https://github.com/dandalandone/POC-EyCommerce/assets/126449551/1306d910-03b9-42ba-a07e-4323222b782c)

- Updated Product Quantity 
![image](https://github.com/dandalandone/POC-EyCommerce/assets/126449551/bb27ceea-1433-4084-9ade-05fe4721737b)

## How to test?

- Open Postman
- click import tab, paste cURL
```
curl --location --request PUT 'http://localhost:3001/api/cart/[insert userID here]' \
--header 'Authorization: Bearer [insert access token here]' \
--header 'Content-Type: application/json' \
--data '{
    "productID": "[insert productID here]",
    "quantity": 3
}'
```
Note: Must have user data and sample product before testing
- Log in as a user to obtain the access token
- Copy the obtained token to the AUthorization Header
- Update the `productID` and `quantity` as needed

2023-08-09 08:22 UTC, 5andrex reviewed
Please update PR's testing instructions.

2023-08-09 13:48 UTC, TreshAnn commented
> Please update PR's testing instructions.

Done. Thanks, sir drex!

2023-08-10 08:05 UTC, brentmillen requested changes

2023-08-10 08:05 UTC, brentmillen commented on apps/api/src/cart/cart.service.ts
> +    }
The exception is already in the productService function. Can you test if it still works correctly without this condition?

2023-08-10 08:05 UTC, brentmillen commented on apps/api/src/cart/cart.service.ts
> +    }
just reuse the validateQuantity for this one

2023-08-10 08:31 UTC, TreshAnn commented on apps/api/src/cart/cart.service.ts
> +    }
![image](https://github.com/dandalandone/POC-EyCommerce/assets/126449551/7dd723e6-5095-445a-904d-edaedde8a664)

2023-08-10 08:34 UTC, TreshAnn commented on apps/api/src/cart/cart.service.ts
> +    }
Done, Sir! Thanks
![image](https://github.com/dandalandone/POC-EyCommerce/assets/126449551/dc0a3788-bebb-4179-9b13-adcb8a1aa522)

2023-08-10 10:25 UTC, 5andrex approved these changes
yields expected results.
LGTM!

2023-08-11 01:50 UTC, brentmillen approved these changes

2023-08-11 01:52 UTC, merged