Revert "[API] Register API Implementation"
dandalandone/POC-EyCommerce pull request #54
Opened 2023-08-10 07:16 UTC by SGVGen

Reverts dandalandone/POC-EyCommerce#53

2023-08-10 08:41 UTC, brentmillen requested changes
See changes for input spaces trimming

2023-08-10 08:41 UTC, brentmillen commented on apps/web/src/components/auth/RegisterForm.tsx
>                  <TextInput
```suggestion
                <TextInput
                  label="Address"
                  placeholder="House No. / Street / Barangay / City / Province"
                  value={inputValues.address}
                  onChange={(event) => handleInputChange(event, 'address')}
                  onBlur={() => handleInputBlur('address')}
                  required
                />
```

then use the function like this for the TextInput

2023-08-10 08:41 UTC, brentmillen commented on apps/web/src/components/auth/RegisterForm.tsx
```suggestion
const [inputValues, setInputValues] = useState({
    address: '',
    region: '',
    // Add more fields here
  });

  const handleInputChange = (event, fieldName) => {
    const { value } = event.target;
    setInputValues((prevValues) => ({
      ...prevValues,
      [fieldName]: value,
    }));
  };

  const handleInputBlur = (fieldName) => {
    setInputValues((prevValues) => {
      const newValue = prevValues[fieldName].trim();
      return {
        ...prevValues,
        [fieldName]: newValue,
      };
    });
  };
```

add this to trim spaces before and after certain TextInput fields

2023-08-11 03:48 UTC, dandalandone approved these changes

2023-08-11 03:49 UTC, brentmillen approved these changes

2023-08-11 03:57 UTC, closed without merging