[Frontend] - Product Gallery Component
dandalandone/POC-EyCommerce pull request #62
Opened 2023-08-16 06:55 UTC by TreshAnn

## Ticket/s

- [Product Gallery Component](https://trello.com/c/WkzgFy11)

## Changes

- Add ProductGallery Component

## Screenshot
- Website View:
![image](https://github.com/dandalandone/POC-EyCommerce/assets/126449551/2daf3f45-c01a-4d00-a8a3-0973299df849)
- Mobile View

![image](https://github.com/dandalandone/POC-EyCommerce/assets/126449551/8b9a12d1-30f7-4b8f-9b22-790dcacdeff8)

## How to test?

-  run **pnpm  run dev**
- After compilation is complete
- Insert to url http://localhost:5173/

2023-08-17 01:42 UTC, 5andrex requested changes
Component does what it needs to do but I suggest to change the image holder's height when the screen is smaller (mobile) because the product image gets stretched. Thanks!

2023-08-17 02:01 UTC, TreshAnn commented
> Component does what it needs to do but I suggest to change the image holder's height when the screen is smaller (mobile) because the product image gets stretched. Thanks!

Done, Sir @5andrex , please check. thanks!

2023-08-17 03:09 UTC, 5andrex approved these changes

2023-08-18 03:03 UTC, dandalandone approved these changes
LGTM, but please address the unused Library

2023-08-18 03:03 UTC, dandalandone commented on packages/ui/package.json
> +    "embla-carousel-react": "8.0.0-rc11",
remove if unused

2023-08-18 03:11 UTC, TreshAnn commented on packages/ui/package.json
> +    "embla-carousel-react": "8.0.0-rc11",
done, sir @dandalandone ! thanks

2023-08-18 03:23 UTC, merged