[Frontend] Payment Details
dandalandone/POC-EyCommerce pull request #65
Opened 2023-08-16 13:43 UTC by KezTimple

## Ticket/s

[-Checkout Page (Payment Details)](https://trello.com/c/WEaB8O5C/98-checkout-page-payment-details)

## Changes

- Add payment details component

## Screenshot

![image](https://github.com/dandalandone/POC-EyCommerce/assets/137742601/2a4245ae-9ccf-44e0-8019-6ba6f47a1680)

## How to test?

- run pnpm dev
- Insert to url http://localhost:5173/
- Click Open Modal Button

2023-08-17 05:40 UTC, TreshAnn requested changes

2023-08-17 05:40 UTC, TreshAnn commented on packages/ui/Card/OrderSummary.tsx
> +      <PaymentDetails totalPrice={totalPrice} deliveryFee={deliveryFee} />
```suggestion
      <PaymentDetails totalPrice={totalPrice} deliveryFee={deliveryFee} />
      <Button fw={400} fullWidth style={{ color: 'black' }}>
        Place Order
      </Button>
```

2023-08-17 05:40 UTC, TreshAnn commented on packages/ui/Card/PaymentDetails.tsx
> +          <Text fw={700}>TOTAL</Text>
```suggestion
          <Text fw={400}>Total:</Text>
```

2023-08-17 07:05 UTC, TreshAnn requested changes

2023-08-17 07:05 UTC, TreshAnn commented on packages/ui/Card/OrderSummary.tsx
```suggestion
import { Card, Flex, Grid, Group, Paper, Text, Button} from '@mantine/core';

```

import button

2023-08-18 03:02 UTC, TreshAnn approved these changes

2023-08-18 03:23 UTC, 5andrex approved these changes
LGTM

2023-08-18 03:27 UTC, merged