chore(back-end)--add-product-schema
dandalandone/POC-EyCommerce pull request #8
Opened 2023-07-26 02:25 UTC by KezTimple

## Ticket/s

- [Product Model](https://trello.com/c/Cxh9JE0W/31-product-model)

## Changes

- Add Product Model Schema

## Screenshot

- N/A

## How to test?

- N/A

2023-07-26 02:42 UTC, dandalandone submitted a review, later dismissed
Move to api/src/products

2023-07-26 07:42 UTC, KezTimple commented
> Move to api/src/products

done sir. moved to api/src/products

2023-07-27 04:04 UTC, 5andrex requested changes

2023-07-27 04:04 UTC, 5andrex commented on apps/api/src/products/schemas/products.schema.ts
> +}
```suggestion
@Prop()
productCategory:  array;
}
```

2023-07-27 17:24 UTC, sandrex-SGV approved these changes

2023-07-28 03:08 UTC, merged